trigger:
- main

pool:
  name: Default  
  demands:
    - Agent.Name -equals vbox 

steps:
- task: JavaToolInstaller@0
  displayName: "Install JDK 11"
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled' # Fix: Explicitly specify JDK source

- task: Maven@3
  displayName: "Build and Run Tests"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml' 
    codeCoverageToolOption: 'JaCoCo'

- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifacts"
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/target'  
    artifactName: 'drop'
