name: Advanced CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature-*
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: "30 11 * * 1,4"  # Runs every Monday and Thursday at 5:00 PM IST

jobs:
  build:
    runs-on: ubuntu-latest  # Use self-hosted runner if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        if: contains(github.ref, 'dotnet')
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Set up Java
        if: contains(github.ref, 'java')
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore dependencies (.NET)
        if: contains(github.ref, 'dotnet')
        run: dotnet restore

      - name: Restore dependencies (Java)
        if: contains(github.ref, 'java')
        run: mvn dependency:resolve

      - name: Build the application (.NET)
        if: contains(github.ref, 'dotnet')
        run: dotnet build --configuration Release

      - name: Build the application (Java)
        if: contains(github.ref, 'java')
        run: mvn clean package -DskipTests

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/Release/
            **/target/
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run NUnit Tests (.NET)
        if: contains(github.ref, 'dotnet')
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

      - name: Run JUnit Tests (Java)
        if: contains(github.ref, 'java')
        run: mvn test

      - name: Upload Test Results (.NET)
        if: contains(github.ref, 'dotnet')
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"

      - name: Upload Test Results (Java)
        if: contains(github.ref, 'java')
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: "**/target/surefire-reports/*.xml"

      - name: Generate Code Coverage Report (.NET)
        if: contains(github.ref, 'dotnet')
        run: |
          dotnet tool install --global reportgenerator
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

      - name: Generate Code Coverage Report (Java)
        if: contains(github.ref, 'java')
        run: mvn jacoco:report

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: |
            **/coverage/
            **/target/site/jacoco/
 
