name: Advanced CI Pipeline

on:
  workflow_dispatch:  # Enables manual trigger from GitHub Actions UI
  push:
    branches:
      - main
      - develop
      - feature-*
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: "30 11 * * 3,5"  # Runs every Wednesday and Friday at 5 PM IST

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        if: contains(github.ref, 'java')
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore dependencies (Java)
        if: contains(github.ref, 'java')
        run: mvn dependency:resolve

      - name: Build the application (Java)
        if: contains(github.ref, 'java')
        run: mvn clean package

      - name: Upload Build Artifacts with Versioning
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.ref_name }}-${{ github.sha }}
          path: |
            **/bin/Release/
            **/target/

      - name: Set Artifact Version
        run: |
          VERSION_NAME="${{ github.ref_name == 'main' && 'release-' || github.ref_name == 'develop' && 'develop-latest' || 'feature-' + github.ref_name }}-${{ github.sha }}"
          echo "Artifact Version: $VERSION_NAME"
          mv **/target/*.jar **/target/$VERSION_NAME.jar

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies (Java)
        if: contains(github.ref, 'java')
        run: mvn dependency:resolve

      - name: Run JUnit Tests (Java)
        if: contains(github.ref, 'java')
        run: mvn test
        continue-on-error: true

      - name: Generate test report
        run: mvn surefire-report:report
        continue-on-error: true  # Even if tests fail, generate the report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.ref_name }}-${{ github.sha }}
          path: target/surefire-reports/
          if-no-files-found: warn  # Logs a warning instead of failing the pipeline

      - name: Run Code Coverage (JaCoCo)
        run: mvn org.jacoco:jacoco-maven-plugin:0.8.10:prepare-agent test org.jacoco:jacoco-maven-plugin:0.8.10:report

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-${{ github.ref_name }}-${{ github.sha }}
          path: |
            **/coverage/
            **/target/site/jacoco/

  deploy:
    runs-on: self-hosted
    needs: test
    if: success()  # Skip deployment if tests or static analysis fail

    steps:
      - name: Deploy Application
        run: echo "Deploying application..."

  notify:
    runs-on: self-hosted
    needs: [build, test, deploy]
    if: failure()  # Runs only if any of the previous jobs fail
    steps:
      - name: Send Failure Notification via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚨 Build Failed: ${{ github.repository }}"
          body: "The latest build of ${{ github.repository }} has failed. Please check the logs in GitHub Actions."
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: "GitHub Actions Bot"
